"""update capitan_id ondelete in games

Revision ID: 79b08576d4fa
Revises: bcb03c338002
Create Date: 2022-09-15 20:51:22.864495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b08576d4fa'
down_revision = 'bcb03c338002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_capitan_id_fkey', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'users', ['capitan_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('games_capitan_id_fkey', 'games', 'users', ['capitan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
