"""update vk_id column in table chats

Revision ID: 96219a9e3796
Revises: 3011073d5f8c
Create Date: 2022-09-14 15:50:54.497312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96219a9e3796'
down_revision = '3011073d5f8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chats', ['vk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    # ### end Alembic commands ###
