"""added current question column in games table

Revision ID: b0af3413dc8d
Revises: e1fc9a3e5689
Create Date: 2022-09-18 20:30:09.446360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0af3413dc8d'
down_revision = 'e1fc9a3e5689'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('current_question', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_current_question'), 'games', ['current_question'], unique=False)
    op.create_foreign_key(None, 'games', 'questions', ['current_question'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_current_question'), table_name='games')
    op.drop_column('games', 'current_question')
    # ### end Alembic commands ###
