"""add foreign keys indexes

Revision ID: bcb03c338002
Revises: d67634a23e26
Create Date: 2022-09-15 20:45:07.479884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb03c338002'
down_revision = 'd67634a23e26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_games_capitan_id'), 'games', ['capitan_id'], unique=False)
    op.create_index(op.f('ix_games_chat_id'), 'games', ['chat_id'], unique=False)
    op.create_index(op.f('ix_questions_author_id'), 'questions', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_author_id'), table_name='questions')
    op.drop_index(op.f('ix_games_chat_id'), table_name='games')
    op.drop_index(op.f('ix_games_capitan_id'), table_name='games')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    # ### end Alembic commands ###
