"""update author_id ondelete in questions

Revision ID: d67634a23e26
Revises: e7549be09983
Create Date: 2022-09-15 20:42:31.600799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67634a23e26'
down_revision = 'e7549be09983'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_author_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_author_id_fkey', 'questions', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
