"""insert questions

Revision ID: e1fc9a3e5689
Revises: 182578ad3691
Create Date: 2022-09-18 19:21:57.522482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

# revision identifiers, used by Alembic.
from app.game.models import QuestionModel, AnswerModel

revision = 'e1fc9a3e5689'
down_revision = '182578ad3691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    session = orm.Session(bind=op.get_bind())
    session.add_all([
        QuestionModel(
            title="Кого решили изобразить на плакате против расизма, потому что они одновременно и белые, и чёрные, "
                  "и азиаты?",
            answer_desc="На агитационных материалах были панды.",
            answers=[AnswerModel(title="панды"), AnswerModel(title="панд"), AnswerModel(title="панда")],
            is_approved=True
        ),
        QuestionModel(
            title="Закончите мысль польского публициста Януша Васильковского: «Чем больше у тебя воспоминаний, тем "
                  "меньше места остаётся на…».",
            answer_desc="«Чем больше у тебя воспоминаний, тем меньше места остаётся на мечты»",
            answers=[AnswerModel(title="мечты"), AnswerModel(title="на мечты")],
            is_approved=True
        ),
        QuestionModel(
            title="Для врагов у неё меч, а для друзей — то, что вам предстоит угадать. Что же это?",
            answer_desc="Тула славится своими оружейниками, поэтому для врагов у неё меч, а для друзей — тульский "
                        "пряник.",
            answers=[AnswerModel(title="тульский пряник")],
            is_approved=True
        ),
        QuestionModel(
            title="Умной женщине они служат для оценки мужчин, а глупой — для самооценки. О чём идёт речь?",
            answer_desc="О комплиментах.",
            answers=[AnswerModel(title="о комплиментах"), AnswerModel(title="комплименты")],
            is_approved=True
        ),
        QuestionModel(
            title="Что американский писатель Стивен Кинг назвал самой большой замочной скважиной в истории "
                  "человечества?",
            answer_desc="Интернет.",
            answers=[AnswerModel(title="интернет")],
            is_approved=True
        ),
        QuestionModel(
            title="В Лондоне XVIII века рог единорога вешали над аптекой, ведро с гвоздями — над скобяной лавкой. "
                  "А над какой лавкой были изображены Адам и Ева?",
            answer_desc="Над фруктовой лавкой, потому что Ева дала Адаму яблоко.",
            answers=[
                AnswerModel(title="над фруктовой лавкой"), AnswerModel(title="лавка с фруктами"),
                AnswerModel(title="над лавкой с фруктами"), AnswerModel(title="лавка с фруктами"),
                AnswerModel(title="с фруктами"), AnswerModel(title="фруктовой лавкой"),
                AnswerModel(title="фруктовая лавка")
            ],
            is_approved=True
        ),
        QuestionModel(
            title="Что аргентинский писатель Хулио Кортасар назвал «глазом насекомого, увеличенным в тысячи раз» и "
                  "«растительным мозгом»?",
            answer_desc="Цветную капусту.",
            answers=[
                AnswerModel(title="цветную капусту"), AnswerModel(title="цветная капуста"), AnswerModel(title="капуста")
            ],
            is_approved=True
        ),
        QuestionModel(
            title="Что, согласно старинной арабской мудрости, порождают сплошные солнечные дни?",
            answer_desc="Пустыню.",
            answers=[AnswerModel(title="пустыню"), AnswerModel(title="пустыни")],
            is_approved=True
        ),
        QuestionModel(
            title="В произведении Евгении Некрасовой ОН качался, как бокал с пресной водой. Назовите ЕГО.",
            answer_desc="Озеро Байкал.",
            answers=[AnswerModel(title="Байкал"), AnswerModel(title="озеро Байкал")],
            is_approved=True
        ),
        QuestionModel(
            title="На эмблеме женского баскетбольного клуба «Вологда-ЧевакАта» изображена баскетболистка с "
                  "жёлто-чёрным мячом в руках, а у самой спортсменки есть ОНО. Назовите ЕГО.",
            answer_desc="Эта баскетболистка – антропоморфная пчела.",
            answers=[AnswerModel(title="жало")],
            is_approved=True
        ),
        QuestionModel(
            title="Карикатурист Эшли Бриллиант справедливо полагает, что жить на земле дорого, зато каждый из нас "
                  "ежегодно получает бесплатный круиз. Что это за круиз?",
            answer_desc="Круиз вокруг Солнца.",
            answers=[AnswerModel(title="вокруг Солнца"), AnswerModel(title="круиз вокруг Солнца")],
            is_approved=True
        ),
        QuestionModel(
            title="В брюхе баня, в носу решето, на голове пупок, одна рука, да и та на спине. Что это?",
            answer_desc="Чайник",
            answers=[AnswerModel(title="чайник")],
            is_approved=True
        ),
        QuestionModel(
            title="Это даётся человеку дважды. Каждый раз бесплатно, а если человек захочет иметь это в третий раз, "
                  "то за это нужно будет заплатить. Что это?",
            answer_desc="Зубы.",
            answers=[AnswerModel(title="зубы"), AnswerModel(title="зуб")],
            is_approved=True
        ),
        QuestionModel(
            title="Круглая, с хвостом и всё отделяет. Кто она?",
            answer_desc="Запятая.",
            answers=[AnswerModel(title="запятая")],
            is_approved=True
        ),
        QuestionModel(
            title="Она расскажет вам о любви ценой собственной жизни. Кто она?",
            answer_desc="Ромашка.",
            answers=[AnswerModel(title="ромашка")],
            is_approved=True
        ),
        QuestionModel(
            title="Из-за себя бью тебя. Из-за тебя бью себя. О чём или о ком речь?",
            answer_desc="Комар.",
            answers=[
                AnswerModel(title="комары"), AnswerModel(title="комар"), AnswerModel(title="о комарах"),
                AnswerModel(title="о комаре")
            ],
            is_approved=True
        ),
        QuestionModel(
            title="Шапка зёрнышек полна. Утром глянул — нет зерна. Что это?",
            answer_desc="Небо и звёзды",
            answers=[
                AnswerModel(title="небо и звезды"), AnswerModel(title="небо и звёзды"),
                AnswerModel(title="звёздное небо"), AnswerModel(title="звездное небо"),
                AnswerModel(title="небо со звёздами"), AnswerModel(title="небо со звездами")
            ],
            is_approved=True
        ),
        QuestionModel(
            title="Она появляется тогда, когда на какое-нибудь определенное действие человек затрачивает наименьшее "
                  "количество движений«. Какое человеческое качество так точно описал Чехов?",
            answer_desc="Грация.",
            answers=[AnswerModel(title="грация")],
            is_approved=True
        ),
        QuestionModel(
            title="Ученый Дэвид Льюис из Англии, проведя исследование, выяснил, что это безопасно только для женщин, "
                  "в то время как для мужчин чревато появлением серьезных болезней.",
            answer_desc="Шопинг",
            answers=[AnswerModel(title="шопинг")],
            is_approved=True
        ),
        QuestionModel(
            title="Статья советской газеты «Правда» содержала следующую информацию: он – космополит, тунеядец и бомж. "
                  "Другая же статья предлагала следующее: «в Советском Союзе он нашел сообщника – и тоже иностранного "
                  "происхождения». Кто они?",
            answer_desc="Гена и Чебурашка",
            answers=[AnswerModel(title="гена и чебурашка"), AnswerModel(title="чебурашка и гена")],
            is_approved=True
        )
    ])
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
