"""update capitan_id column in games table

Revision ID: e7549be09983
Revises: 96219a9e3796
Create Date: 2022-09-14 16:47:11.885499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7549be09983'
down_revision = '96219a9e3796'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'capitan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'capitan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
